name: Upload to PyPI
on:
  release:
    types: [published]
jobs:
  release-build:
    runs-on: ubuntu-latest
    environment: release
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: build release distributions
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools
          python -m pip install build
          python -m build
      - name: upload windows dists
        uses: actions/upload-artifact@v4
        with:
          name: release-dists-${{ matrix.python-version }}
          path: dist/${{ matrix.python-version }}/
  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
    environment: release
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    permissions:
      id-token: write
    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists-${{ matrix.python-version }}
          path: dist/-${{ matrix.python-version }}/
      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
